# _target_: models.sequence.SequenceModel
_name_: model
layer:
  - _name_: hgru2d
    param_share: ${model.param_share}
    use_lower_bound: ${model.use_lower_bound}
    causal: ${model.causal}
    use_real: ${model.use_real}
  - _name_: glu
    act_fun: swish
    glu_expand_ratio: ${model.expand_ratio_glu}

# hgru
param_share: True
use_lower_bound: True
causal: False
use_real: False

tno_head: 1
tno_max_l: 1024
tno_type: 4
tno_use_decay: False
tno_gamma: 0.999
tno_dpb_dim: 16 #min(d_model//4, 64)
expand_ratio_tno: 2
expand_ratio_glu: 2
dpb_type: 4
dpb_layers: 1

flash_s: 0
flash_max_position_embed: 0
flash_linear_s: 0
flash_linear_max_position_embeddings: 0
lg_local_heads: 0
lg_linear_heads: 0
lg_local_chunk_size: 0
ls_attn_heads: 0
ls_attn_window_size: 0
ls_attn_max_seq_len: 0
performer_heads: 0
performer_approx_attn_dim: 0
use_softmax: true
cosformer_heads: 0 
cosformer_max_length: 0
linformer_max_seq_len: 0

residual: R
dropout: 0.1
encoder:
  _name_: position
  dropout: 0.1
# init:
#   init: normal  # Parameter initializer to use
#   init_range: 0.1  # Parameters initialized by U(-init_range, init_range)
#   init_std: 0.02  # Parameters initialized by N(0, init_std)