# _target_: models.sequence.SequenceModel
_name_: model
layer:
  - _name_: ls_attn
    n_heads: 8
    max_seq_len: 4000
    num_landmarks: 32
    window_size: 8
  - _name_: ff
    expand: 3
    dropout: null
    transposed: False

heads: 10
residual: R
dropout: 0.1
encoder:
  _name_: position
  dropout: 0.1
# init:
#   init: normal  # Parameter initializer to use
#   init_range: 0.1  # Parameters initialized by U(-init_range, init_range)
#   init_std: 0.02  # Parameters initialized by N(0, init_std)