# _target_: models.sequence.SequenceModel
_name_: model
layer:
  - _name_: performer_attn
    n_heads: 8
    approx_attn_dim: 64
  - _name_: ff
    expand: 3
    dropout: null
    transposed: False

n_layers: 6
d_model: 512
residual: R
prenorm: true
dropout: 0.1
encoder:
  _name_: position
  dropout: 0.1
# init:
#   init: normal  # Parameter initializer to use
#   init_range: 0.1  # Parameters initialized by U(-init_range, init_range)
#   init_std: 0.02  # Parameters initialized by N(0, init_std)