# _target_: models.sequence.SequenceModel
_name_: model
layer:
  - _name_: flash_attn
    s: 128
    eps: 1e-5
    max_position_embeddings: 2048

residual: R
dropout: 0.1
encoder:
  _name_: position
  dropout: 0.1
# init:
#   init: normal  # Parameter initializer to use
#   init_range: 0.1  # Parameters initialized by U(-init_range, init_range)
#   init_std: 0.02  # Parameters initialized by N(0, init_std)