# _target_: models.sequence.SequenceModel
_name_: model
layer:
  - _name_: localattn
    n_heads: 8
    chunk_size: 64
    act_fun: relu
    norm_type: ${model.norm}
    use_orpe: true
  - _name_: linearattn
    n_heads: 8
    act_fun: elu
    norm_type: ${model.norm}
    use_orpe: true
  - _name_: glu
    act_fun: swish

residual: R
dropout: 0.1
encoder:
  _name_: position
  dropout: 0.1
# init:
#   init: normal  # Parameter initializer to use
#   init_range: 0.1  # Parameters initialized by U(-init_range, init_range)
#   init_std: 0.02  # Parameters initialized by N(0, init_std)